### ISSUE TITLE
CUDA ZFP produces 0 for arrays beyond a size

### ISSUE THREAD

**Issue by data-panda** [LLNL/zfp#121] opened 2021-02-01 09:54 UTC
We have this weird issue wherein if we compress and decompress an array bigger that `512^3`, the resulting decompressed data is part filled with complete zeros (`0.0e+0`). In one of the machine where we ran, it exactly produces this behavior from `513^3` (float) onwards array, whereas on another machine, it starts breaking somewhere beyond `512^3` but not exactly at `513^3`. For reproducibility sake, I compressed and uncompressed a float array of size `768 x 768 x 768` (also reproducible with `1024 x 1024 x 1024`). I filled the array with exponential function as in `examples/simple.c` and also with a cosine wave function, source being at `z = 0`. The behavior of decompressed data containing zeros is *exactly* the same. I have attached the snapshot at the mid (x - z, y normal) plane for serial as well as cuda run for you to look at how the zeros show up in the case of CUDA_ZFP. In the case of cosine wave, I have highlighted the points on the slice where `value == 0.` with magenta color, since the neighboring points are of very small value compared to the wave source, making the visibility difficult.

![image](https://user-images.githubusercontent.com/9045578/106440253-a291b300-649e-11eb-8d82-2a4772a7f01c.png)

You can reproduce the same result and behavior with the help of this gist which contains the high level C APIs as prescribed in the `examples/simple.c`: https://gist.github.com/data-panda/1f164852fbdadc7364f5cdf8a82ab065.

Compile: `icc -O3 -fopenmp simple_0bug_reproducer.c -lm -lzfp` 

Tested this with zfp release 0.5.5 and current branch `develop`. In both the cases, I reproduce the same behavior.

I am not sure if the *ISSUE* https://github.com/LLNL/zfp/issues/105 and this has the same root cause but I am far from the 4GB limit. The uncompressed file size when written to disk is `~1.8GB`. 

Am I missing something here?

**Comment by lindstro** [comment] 2021-02-01 17:12
I can reproduce this issue using CUDA 10.1 and both icc 19.0 and gcc 4.9.  This issue probably is not related to #105 for 768^3 grids, but possibly for 1024^3 since 1024^3 * sizeof(float) = 4 GB.  Portions of the code that use signed ints would be limited to 2 GB.

We are aware that the CUDA implementation is not as robust for very large data sets and will be looking at weeding out bugs over the coming weeks.

In the meantime, the only quick fix I can suggest is to break the array into smaller pieces (whose dimensions are multiples of 4) and to compress them separately.  One way to achieve this without explicitly having to reorganize the data is to use zfp's [striding mechanism](https://zfp.readthedocs.io/en/release0.5.5/high-level-api.html#c.zfp_field).

**Comment by data-panda** [comment] 2021-02-01 17:51
Thanks @lindstro. If I move from 768 to 1024, the band of zeros increase (?). it seems like anything beyond a certain data size is being decompressed as zeros (or compressed as zeros). In the case of 1024, if everything is zero then i suspect I am seeing the same behavior as mentioned in #105 . Will update!

**Comment by lindstro** [comment] 2021-02-01 18:37
I cannot think of a good reason why we're seeing this behavior.  It's also unclear whether the issue is in the compressor or decompressor (or both), e.g., does the compressed output match what the serial implementation outputs?

It is somewhat telling that this appears to occur only along one axis (the z-axis, AFAICT, which should be the most slowly various one).  This suggests that the compressed stream is somehow being truncated.  What if you halve the rate to 4 bits/value?  I can investigate this further myself when I have more time, but it won't be until later this week.

**Comment by lindstro** [comment] 2021-02-01 20:40
Something else that occurred to me: zfp does not only need to address array elements (via indices) and bytes (via pointers), but also bits (via bit offsets into the compressed stream).  The largest 32-bit signed bit offset is 2^31 - 1.  For a data set of size 768^3 at a rate of 8 bits/value, you can address only (2^31 - 1) / 768^2 * 8 ~ 455 out of 768 slices, which judging by your visualizations appears to agree closely with where the data is cut off.  The bit offset *should* be a 64-bit unsigned quantity, but I've seen places in the CUDA code where 32-bit ints are (incorrectly) used.

This gives a plausible explanation for the behavior you're observing, and I'm guessing the problem will go away if you change the rate to 4 bits/value for the 768^3 data set.  I'll see if I can confirm this and will keep you posted.

**Comment by lindstro** [comment] 2021-02-02 01:53
I can confirm my suspicions.  First, using checksums I've verified that the compressed data matches between the serial and CUDA backends (for 768^3 arrays), so the issue is primarily with the decompressor, not compressor.  Also, decompression fails when the rate is above 2^31 / 768^3 ~ 4.74 (e.g., a rate of 4.5 works fine but 4.75 does not).

It appears [this line](https://github.com/LLNL/zfp/blob/abc76964768e895d12a106c4e1f8ee8518376368/src/cuda_zfp/decode.cuh#L43) is to blame.  Here `(block_idx * maxbits)` is the bit offset, which is computed as a 32-bit int.  Adding a cast makes your example work.  There's a similar missing cast in the `BlockWriter` that causes issues with larger arrays.

I've pushed a (temporary) fix to `develop`.  Please confirm that it addresses your issue.

Note that this addresses the bit offset issue only.  There are potentially other issues with addressing elements and/or bytes that might occur for larger arrays, though I confirmed that arrays up to 1200^3 now work.  As I said, we'll be looking at these issues over the coming weeks.

**Comment by data-panda** [comment] 2021-02-02 03:28
@lindstro i had already did the hashums on the compressed file and was sure the error was in decompression. Thanks for confirming the same. I will checkout he bugfix that you pushed to `develop` and confirm if it works for me.

**Comment by data-panda** [comment] 2021-02-02 05:58
works for `(512 --> 1250]`. Tried 1300^3 but hit the malloc limits on the system resulting in segfault. So I think this fix works.

**Comment by amikstcyr** [comment] 2021-02-02 09:07
Great for finding that one!

**Comment by lindstro** [comment] 2021-02-10 20:11
@data-panda Can I close this issue?

**Closed** 2021-02-12 17:17 UTC
Labels: bug
