### ISSUE TITLE
ZFP for HIP instructions

### ISSUE THREAD

**Issue by pkoosha** [LLNL/zfp#142] opened 2021-08-16 16:33 UTC
I am trying to build ZFP for HIP and noticed that you have it as a feature however I am not able to find any documentation on what to enable and examples to use AMD GPUs for ZFP.
I built feature/hip-support and when passing the ctest, I did rocm-smi and it shows the GPU is not being used.
Could you help me with some instructions on this issue? Appreciate you!

**Comment by lindstro** [comment] 2021-08-16 16:47
You first need to build zfp with HIP support and then enable the HIP execution policy at run time.  reStructuredText documentation for both is available in `docs/source/execution.rst` and `docs/source/installation.rst`.  If you have Sphinx installed, you can 'build' the documentation as html, for instance, via

```
cd docs
make
```

which should result in `docs/build/html/index.html`.

Note that we are in the process of adding HIP support for variable-rate compression, but this feature still has some issues and those tests are currently failing.  The fixed-rate mode should work, however.

**Comment by lindstro** [comment] 2021-08-23 19:54
@pkoosha Please let me know if your questions are answered in the documentation.  If so, I'd like to go ahead and close this issue.

**Comment by pkoosha** [comment] 2021-08-30 21:22
It has not been resolved.

I am running the following command I see the following error:

cmake .. -DCMAKE_INSTALL_PREFIX=$PWD/install-zfp -DZFP_WITH_HIP=ON -DHIP_PATH=/opt/rocm-4.2.0/lib/cmake -DAMDDeviceLibs_DIR=/opt/rocm-4.2.0/lib/cmake/AMDDeviceLibs/ -Damd_comgr_DIR=/opt/rocm-4.2.0/lib/cmake/amd_comgr/ -Dhsa-runtime64_DIR=/opt/rocm-4.2.0/lib/cmake/hsa-runtime64/ -DROCclr_DIR=/opt/rocm-4.2.0/lib/cmake/rocclr/ -Dhipcub_DIR=/opt/rocm-4.2.0/lib/cmake/hipcub/ -Drocprim_DIR=/opt/rocm-4.2.0/lib/cmake/rocprim/ -Dhip_DIR=/opt/rocm-4.2.0/lib/cmake/

CMake Error at src/CMakeLists.txt:37 (hip_add_library):
  Unknown CMake command "hip_add_library".

**Comment by lindstro** [comment] 2021-08-30 22:04
This is how we're building zfp with hip on Linux:

`cmake .. -DZFP_WITH_HIP=ON -DHIP_PATH=/opt/rocm-4.2.0/hip -DZFP_WITH_OPENMP=OFF -DCMAKE_CXX_STANDARD=11 -DCMAKE_C_STANDARD=11 -DCMAKE_C_COMPILER=hipcc -DCMAKE_CXX_COMPILER=hip`

**Comment by pkoosha** [comment] 2021-09-08 17:00
I confirm that my issue have been resolved. However, when using RoCM 4.2 I am getting conflicting types for int8 and uint8 from ZFP.h include file and hip_vector_types.h.

`/home/project/zfp/zfp/build/install-dir/include/zfp/types.h:59:23`: error: conflicting types for ‘int8’
  `typedef signed char int8`
   `/opt/rocm-4.2.0/hip/include/hip/amd_detail/hip_vector_types.h:1534:32`: note: previous declaration of ‘int8’ was here
 `typedef union { int data[8]; } int8;
`

I was wondering do you support a specific version of RoCM libraries for having ZFP features? Thanks

**Comment by lindstro** [comment] 2021-09-08 18:00
I cannot reproduce this error, even though I do see that clashing type definition in `hip_vector_types.h`.  What operating system are you on?  Are you including specific hip headers to trigger this, or does it occur when building zfp?

We plan on eventually replacing `int8` with `int8_t` and similar.  We'll be more motivated to make this change sooner rather than later (at least on the hip branch) if there's an incompatibility with hip.

We've successfully built zfp this way on Linux with RoCM 4.0, 4.1, 4.2, and 4.3.  I should note that the build line above got cut off.  The last macro should of course read `-DCMAKE_CXX_COMPILER=hipcc`.

**Comment by pkoosha** [comment] 2021-09-17 16:30
This is to confirm that I was able to build and use ZFP API for AMD inside my application after building everything with GCC 11. Thank you for your help

**Comment by lindstro** [comment] 2021-09-17 16:39
Glad to hear it.  Our HIP support is still in an experimental phase, with only fixed-rate mode working properly.  We'll be sure to debug and test this feature more thoroughly before it's officially released.

**Closed by lindstro** 2021-09-17 16:39 UTC
